---
title: "Facebook Survey Dashboard"
author: "Delphi Group"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_document:
    code_folding: hide
params:
  source: "fb-survey"
  signal: "raw_cli"
---

```{r, include = FALSE}
source("dashboard_functions.R")
```


## Sampling

```{r, fig.width = 7, fig.height = 5}

df_fb1_st = covidcast_signal("fb-survey", "raw_cli", geo_type = "state")
n_per_day = df_fb1_st %>% 
  group_by(time_value) %>% 
  summarize(n = sum(sample_size)) 

ggplot(n_per_day, aes(x = time_value, y = n)) + 
  geom_line() + geom_point() + theme_bw() + 
  labs(x = "Date", y = "Number of Responses",
       title = sprintf("Total responses: %i, mean per day: %i", 
                       round(sum(n_per_day$n)), round(mean(n_per_day$n)))) +
    date_scale

df_fb1 = covidcast_signal("fb-survey", "smoothed_cli")
county_per_week = df_fb1 %>% 
  group_by(time_value) %>%
  summarize(n = n())

ggplot(county_per_week, aes(x = time_value, y = n)) + 
  geom_line() + geom_point() + theme_bw() + 
  labs(x = "Date", y = "Number of Counties", 
       title = sprintf("Unique counties: %i, mean per week: %i", 
                       length(unique(df_fb1$geo_value)), 
                       round(mean(county_per_week$n)))) +
    date_scale
```

## Coverage

```{r, fig.width = 10, fig.height = 8}
county_totals = df_fb1 %>% 
  group_by(geo_value) %>%
  summarize(value = n()) %>% ungroup() %>%
  filter(substr(geo_value,3,5) != "000") 

county_totals$time_value = "2020-04-15"
county_totals$issue = "2020-04-15"
attributes(county_totals)$metadata$geo_type = "county"
class(county_totals) = c("covidcast_signal", "data.frame")

plot(county_totals, title = "Which counties ever appear in our CLI signals?",
     choro_col = c("#D3D3D3", "#FFC0CB"), choro_params = list(breaks = c(0, 1), 
                                                              legend_width = 5))
```

